name: Executar Scraper TCM-PA

on:
  schedule:
    # Executa diariamente às 05:00 UTC (02:00 no horário de Brasília)
    - cron: '0 5 * * *'
  workflow_dispatch: # Permite executar manualmente no painel do GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar Dependências Python
        run: pip install -r requirements.txt

      - name: Executar Scraper
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python scraper.py
